services:
  dev:
    hostname: vic-starter
    build: ./
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_started
      redis:
        condition: service_started
      adminer:
        condition: service_started
      mailcatcher:
        condition: service_started
    ports:
      - "80:80"
    environment:
      - SERVER_NAME=:80
      - APP_ENV=dev
      - DEFAULT_URI=http://127.0.0.1:8000/
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-toor}
      - MYSQL_USER=${MYSQL_USER:-api}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-toor}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-api}
      - MYSQL_HOST=vic-starter-mysql
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - DATABASE_URL=mysql://${MYSQL_USER:-api}:${MYSQL_PASSWORD:-toor}@${MYSQL_HOST:-vic-starter-mysql}:${MYSQL_PORT:-3306}/${MYSQL_DATABASE:-api}?serverVersion=8.0
      - REDIS_DSN=redis://toor@vic-starter-redis:6379
      - MESSENGER_TRANSPORT_DSN=redis://toor@vic-starter-redis:6379
      - LOCK_DSN=redis://toor@vic-starter-redis:6379
      - MAILER_DSN=smtp://vic-starter-mailcatcher:1025
    volumes:
      - .:/app

  mysql:
    hostname: vic-starter-mysql
    image: mysql:8.4.5
    restart: unless-stopped
    command:
      - "--log_bin_trust_function_creators=1"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-P", "3306" ]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-toor}
      - MYSQL_USER=${MYSQL_USER:-api}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-toor}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-api}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - TZ=Europe/Paris
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    hostname: vic-starter-redis
    image: redis:8.0.0
    restart: unless-stopped
    command: "redis-server --port 6379 --save 20 1 --loglevel warning --requirepass toor"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis_data:/data

  adminer:
    hostname: vic-starter-adminer
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8001:8080"
    environment:
      ADMINER_DEFAULT_SERVER: vic-starter-mysql
      ADMINER_DESIGN: nette

  mailcatcher:
    hostname: vic-starter-mailcatcher
    image: sj26/mailcatcher:latest
    restart: unless-stopped
    ports:
      - "1080:1080"

volumes:
  mysql_data:
  redis_data:
